apiVersion: batch/v1
kind: Job
metadata:
  name: create-kafka-topics
spec:
  template:
    spec:
      containers:
        - name: kafka-topic-creator
          image: bitnami/kafka:3.6.1
          command:
            - /bin/bash
            - -c
            - |
              echo "Waiting for Kafka to be ready..."
              sleep 30  # Give Kafka time to start

              echo "Creating Kafka topics..."
              KAFKA_CMD="kafka-topics.sh --bootstrap-server kafka-service:9092 --if-not-exists --create --replication-factor 1 --partitions 1 --topic"

              # User related topics
              $KAFKA_CMD add-user
              $KAFKA_CMD password-reset-user
              $KAFKA_CMD update-password-user
              $KAFKA_CMD update-profile-user
              $KAFKA_CMD block-user

              # Doctor related topics
              $KAFKA_CMD add-doctor
              $KAFKA_CMD password-reset-doctor
              $KAFKA_CMD update-password-doctor
              $KAFKA_CMD update-profile-doctor
              $KAFKA_CMD block-doctor
              $KAFKA_CMD verification-request
              $KAFKA_CMD add-slot
              $KAFKA_CMD remove-slot

              # Admin related topics
              $KAFKA_CMD add-admin

              # Wallet related topics
              $KAFKA_CMD update-bookAppointment-user-wallet
              $KAFKA_CMD update-bookAppointment-doctor-wallet
              $KAFKA_CMD update-bookAppointment-admin-wallet
              $KAFKA_CMD update-cancelAppointment-user-wallet
              $KAFKA_CMD update-cancelAppointment-doctor-wallet

              # Notification related topics
              $KAFKA_CMD send-otp-email
              $KAFKA_CMD send-forgotPassword-email
              $KAFKA_CMD verified-Doctor-email
              $KAFKA_CMD document-rejection-mail
              $KAFKA_CMD document-approval-mail

              echo "Kafka topics created successfully!"
      restartPolicy: Never
  backoffLimit: 6  # Increased to ensure retries
