name: healthx-user-service-ci-cd

on:
  push:
    branches:
      - "main"  # Use "main" if that's your default branch
    paths:
      - "userService/**"  # Trigger on any change in the repository

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: docker build -t logeshc12/healthx-user-service:latest .

      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - run: docker push logeshc12/healthx-user-service:latest
